{...}: {
  networking.domain = "cdbrdr.com";

  storage.csi.nfs = {
    server = "192.168.0.10";
    share = "/exports/kubernetes";
  };

  nixidy.target.branch = "env/prod";
  nixidy.extraFiles."README.md".text = ''
    # Rendered manifests

    The manifests in this branch are generated by [nixidy](https://github.com/arnarg/nixidy).
  '';
}
