apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: sops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/sops-secrets-operator
    repoURL: https://github.com/arnarg/cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
