apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/cilium
    repoURL: https://github.com/arnarg/cluster.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
