apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: traefik-secrets
spec:
    suspend: false
    secretTemplates:
        - name: acme-env
          stringData:
            CF_DNS_API_TOKEN: ENC[AES256_GCM,data:nDDu4qscrcWoOxmTh+iKuHhAEwPD4RSTBUvDrci/nA2i+XBgDkFyfQ==,iv:tTClXBtguOItvoqto6kpXDRzk1A5FST+BjrvgJJmT6A=,tag:sLa+tSOjp/0itEzYOGy2nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age104h7jf5d9vkvmgqv2ecxtnmltt76tuzyz5sy3t0kp9vxvmzjvvhsz7y9md
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUDVuUTdsaDFQcm5SQlFj
            c0dWdy9UcnI1R3dHMWlDSEc3aUYzUlJoZTBnCm4wZ29EMnduNDJxOEdpeFRWTGt3
            WUV1NlNhbGQvRU1zK2txWmg1NmViTk0KLS0tIE1XRkY5Wm9qTlFaN2NWcVIwaGkz
            WTJUMzYyTG12TUNxU005SjY1NFpjRGsK8i7Vkk4lj+z07+UO8jWlNgO/ZesSgDzG
            rn+0jkBTsnUwnlh+X9aGmmiDhSpSUu/ElstorfQ2tn12f0Dsr+U5Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T10:14:14Z"
    mac: ENC[AES256_GCM,data:/5kF6ogGKE85NQnNiCpoHDV7x4NuzXOL1FEIZ4N93Plfj7vQBIrpKbI64W3xM/JYiwtbDPB5AyHSXvR0iHP2YmClrT1Pp80VxueObuVbK9CipY19p/qCsMnDqCrkar8E438Th6sORYargfGfjo0ueWqHO3++OXtAHM4X2SNApow=,iv:FCpZlGd3FljM3XykI1L6XHnduukLk1QwmILl2iMqa9M=,tag:JvQEcssVNuBrO03/1MKgFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
