apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: pipelines
    app.kubernetes.io/instance: open-webui
    app.kubernetes.io/name: pipelines
  name: open-webui-pipelines
  namespace: open-webui
