apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: null
  labels:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
