apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: shiori-secrets
  namespace: shiori
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraWpKY2FzSnZjMGJJNUtx
        WG1sakZsQXRHUHZzT2dqcnlpeFIvZ1BUcWhnCnJOd0daVmJBNXlTdlhXT2IwdFo4
        M2V4NHZibzJuQW5qR2draHJWL1dhYW8KLS0tIDhYVlIvS2tlUEkzNTRpYTQ3VmR1
        U1F6Z0tadVpCQzkyTjFaRWhFc3JlQUUKvDmQa/9MrrxSEytUaSPcH8mf8S9hsdnO
        JTGMLJq/qBPw+ZEQ652ugRjCVsYxm5RvbodzwfHLsL+uevaagnSEkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age104h7jf5d9vkvmgqv2ecxtnmltt76tuzyz5sy3t0kp9vxvmzjvvhsz7y9md
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: "2024-05-07T13:54:18Z"
  mac: ENC[AES256_GCM,data:/NNQxoGmwmzLcF+/CZ3o5tl+890V31gf3sTDfF6Vj8fDXUctig3PS3f08o3oveXWRnQ5xzGXXrFJ7bryVcP3EHMgUSySh8lRxoaTOLtIACLsctmmuDx4lbS38J3gfIgHHcyNBYjPtWkh1tj2unJpaQK6CqudsmZpru1BFhWdvAo=,iv:gfiKyuujJeYBlYmnnTCO0i2g9kAigafR4DqSJc8QR8E=,tag:Nc3TGVpZ0RwJA0C6OKyxZA==,type:str]
  pgp: []
  version: 3.8.1
spec:
  secretTemplates:
    - name: shiori-creds
      stringData:
        databaseConn: ENC[AES256_GCM,data:EKaEQPvWwKZcvq7p09wGN7w14SRqLJ1zvJYu7F/DZXRyw2WJ6RcKGIFCqX1iyp4dL84yWbjR3Ba3WoKUp+a3tA625Bi/u/bqgeqXLVsg,iv:deWGi2yPc0ougwyokty+am2eRL20WRJrpwMMbskzgqA=,tag:yePOwlM8oPWBbGSAC0KRnA==,type:str]
        secretKey: ENC[AES256_GCM,data:aFiI191J2UlSyk1mHJ6VokLPragl3eMlZ+te1+mJaNiuc2CxH+mIs9hhBiiRt1IgYGozS3omtHqtvB95D5MBfQ==,iv:28nKkW2eCNxIVXDmxu0A+BM5aGSgKVTpwTkTepsen9M=,tag:j0H70SWwuWAokwEZKnvpGw==,type:str]
  suspend: false
