apiVersion: v1
data:
  policy.csv: ""
  policy.default: ""
  scopes: '[groups]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v2.9.2
    helm.sh/chart: argo-cd-5.51.4
  name: argocd-rbac-cm
  namespace: argocd
