apiVersion: v1
kind: Service
metadata:
  name: miniflux
  namespace: miniflux
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: miniflux
  type: ClusterIP
