apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: miniflux-secrets
  namespace: miniflux
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSXBmSThQSTRFRU1lUm1O
        TVlFL2RjdFNWQTlNdFc5VU5EYVp1Y0wwQWpRCnIrVTdKbld2MHc0UWpLSXoyT3dQ
        WlZ0a1EwY0VBMTFDNTRtSTZnb0JlNncKLS0tIDkyY1RTSHZiSnFqTnZEWDc3dEQ2
        N2pOZzkwL1hoK0oxaEhnaFdUL1BlQ0EK4OOiSY8hqN4Jk7XSdllcty6eEp/C4rKi
        H9tQFuCy4IQAfHbDkWOilnTfRVO55f96Bi2LISIk/vgeTOCJjPP37w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age104h7jf5d9vkvmgqv2ecxtnmltt76tuzyz5sy3t0kp9vxvmzjvvhsz7y9md
  azure_kv: []
  encrypted_regex: ^(data|stringData)$
  gcp_kms: []
  hc_vault: []
  kms: []
  lastmodified: "2023-11-06T10:14:34Z"
  mac: ENC[AES256_GCM,data:szELl4ihURL6U7szJU0oB0jJWS+s13GYRywrv6wjQk8EgDQQNZa68xZP3ShhjmRUP+3eyFt2cSOQHoNarmhqDFV5l4UIPAEHDRSs4h6T1vdJDEQsVchI2xPrwP2/YGB6aeB2AJc07Pazca9Xp4J7/72ftusRfUnbOCV42UdUqkE=,iv:fQeNA1/wuDwsB5uQ1knddmwCgkJMdoxlcsJnD3jT/DE=,tag:B+42L/umMttKS1TRRZkcMw==,type:str]
  pgp: []
  version: 3.7.3
spec:
  secretTemplates:
    - name: miniflux-creds
      stringData:
        adminPassword: ENC[AES256_GCM,data:Zcba7Sr2HXOL/O9vOY3gOWcVvc88rRFL,iv:upTcnBqJDPUi5/bqUFeS//2dXj7+joXHhNGObSDkrCc=,tag:5UPAh90y+oQ8PhSvWlW5Rw==,type:str]
        adminUser: ENC[AES256_GCM,data:8TbCjDk=,iv:q/rKvgq5NWP6CZtoyp61jZPWRJ3EaT6fLr2vwSUDpJg=,tag:d1DJQBlbm4BXMuWPAbxeyw==,type:str]
        databaseConn: ENC[AES256_GCM,data:IUdmyu3hFlyj6n9oNA7fiGzjVupKHC0DNYHW7oPCRBerZPOw0HsFivYL+EtQ9yEopHMaoswqhUONMrrI7gy78gWNnNrt1qnD/qY4x2+jUNEiO2xId66Kr7604iT5zYeUzMOdHMyYat1C6MaD,iv:qSHoJrlFgRKx91F6inNkxTLZEh6cBrVZ7yoOTh1vOn4=,tag:RIjVsvNJDt2fBkF9sMmzWQ==,type:str]
  suspend: false
