apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-driver-nfs
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./csi-driver-nfs
    repoURL: https://github.com/arnarg/cluster.git
    targetRevision: env/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
