apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    path: traefik
    repoURL: https://github.com/arnarg/cluster.git
    targetRevision: env/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
