apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: sops
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sops-secrets-operator
    app.kubernetes.io/version: 0.11.4
    helm.sh/chart: sops-secrets-operator-0.17.4
  name: sops-sops-secrets-operator
