apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: 1password-connect
    app.kubernetes.io/name: connect
  name: onepassword-connect-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepassword-connect-operator
subjects:
  - kind: ServiceAccount
    name: onepassword-connect-operator
    namespace: 1password
