apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: 1password-connect
    app.kubernetes.io/name: connect
  name: onepassword-connect
  namespace: 1password
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onepassword-connect
  template:
    metadata:
      labels:
        app: onepassword-connect
        app.kubernetes.io/component: connect
        version: 1.7.3
    spec:
      containers:
        - env:
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  key: 1password-credentials.json
                  name: op-credentials
            - name: OP_BUS_PORT
              value: "11220"
            - name: OP_BUS_PEERS
              value: localhost:11221
            - name: OP_HTTP_PORT
              value: "8080"
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-api:1.7.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-api
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 200m
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 999
            runAsUser: 999
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
        - env:
            - name: OP_HTTP_PORT
              value: "8081"
            - name: OP_SESSION
              valueFrom:
                secretKeyRef:
                  key: 1password-credentials.json
                  name: op-credentials
            - name: OP_BUS_PORT
              value: "11221"
            - name: OP_BUS_PEERS
              value: localhost:11220
            - name: OP_LOG_LEVEL
              value: info
          image: 1password/connect-sync:1.7.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /heartbeat
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
          name: connect-sync
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 999
            runAsUser: 999
          volumeMounts:
            - mountPath: /home/opuser/.op/data
              name: shared-data
      tolerations: []
      volumes:
        - emptyDir: {}
          name: shared-data
        - name: credentials
          secret:
            secretName: op-credentials
