name: Generate Kubernetes manifests

on:
  push:
    branches:
      - main
    paths-ignore:
      - manifests/**

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v2

    - shell: bash
      run: |
        git checkout -B promote/env/prod

        nix run .#generate

        echo "BRANCH=promote/env/prod" >> "$GITHUB_ENV"
        echo "COMMIT_MESSAGE=chore(prod): promote to prod ${{github.sha}}" >> "$GITHUB_ENV"

    - uses: EndBug/add-and-commit@v9
      id: commit
      with:
        default_author: github_actions
        message: ${{env.COMMIT_MESSAGE}}
        fetch: false
        push: --set-upstream origin ${{env.BRANCH}} --force

    - uses: thomaseizinger/create-pull-request@1.4.0
      if: ${{ steps.commit.outputs.pushed == 'true' }}
      with:
        github_token: ${{github.token}}
        head: ${{env.BRANCH}}
        base: main
        title: ${{env.COMMIT_MESSAGE}}
