name: Generate Kubernetes manifests

on:
  push:
    branches:
      - main
    paths-ignore:
      - manifests/**

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          extra-experimental-features = nix-command flakes

    - uses: DeterminateSystems/magic-nix-cache-action@v7

    - uses: arnarg/nixidy/actions/switch@main
      with:
        environment: .#prod

    - uses: EndBug/add-and-commit@v9
      id: commit
      with:
        default_author: github_actions
        message: "chore: promote to prod ${{github.sha}}"
        fetch: false
        new_branch: promote/env/prod
        push: --set-upstream origin promote/env/prod --force

    - uses: thomaseizinger/create-pull-request@1.4.0
      if: ${{ steps.commit.outputs.pushed == 'true' }}
      with:
        github_token: ${{github.token}}
        head: promote/env/prod
        base: main
        title: "chore: promote to prod ${{github.sha}}"
