name: LLM manifest review

permissions:
  pull-requests: write

on:
  pull_request_target:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - manifests/**

jobs:
  llm-review:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '.github/llm-review/requirements.txt'

      - name: Intall dependencies
        run: |
          pip install -r .github/llm-review/requirements.txt

      - name: Run LLM review
        env:
          GITHUB_PR_ID: ${{ github.event.pull_request.number }}
          HYPERBOLIC_API_KEY: ${{ secrets.HYPERBOLIC_API_KEY }}
        run: |
          python .github/llm-review/main.py
