name: Update nixhelm

on:
  # If you want to run this workflow manually.
  workflow_dispatch:

  # Run every saturday at 8:00
  schedule:
    - cron: '0 8 * * 6'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            extra-experimental-features = nix-command flakes

      - shell: bash
        run: |
          git checkout -B promote/env/prod

          nix flake lock --update-input nixhelm

      - uses: EndBug/add-and-commit@v9
        id: commit-nixhelm
        with:
          default_author: github_actions
          message: "chore(prod): update nixhelm"
          fetch: false
          push: false

      - shell: bash
        if: ${{ steps.commit-nixhelm.outputs.committed == 'true' }}
        run: |
          nix run .#nixidy -- switch .#prod

          echo "BRANCH=promote/env/prod" >> "$GITHUB_ENV"

      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          default_author: github_actions
          message: "chore(prod): promote to prod ${{github.sha}}"
          fetch: false
          push: --set-upstream origin ${{env.BRANCH}} --force

      - uses: thomaseizinger/create-pull-request@1.4.0
        if: ${{ steps.commit.outputs.pushed == 'true' }}
        with:
          github_token: ${{github.token}}
          head: ${{env.BRANCH}}
          base: main
          title: Update nixhelm input
